In [13]:
## imports
! pip install plotnine
import pandas as pd
import numpy as np
import plotnine
from plotnine import *
import random

## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from datetime import datetime, timedelta

Collecting plotnine
  Downloading plotnine-0.13.6-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: matplotlib>=3.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotnine) (3.8.4)
Requirement already satisfied: pandas<3.0.0,>=2.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotnine) (2.2.2)
Collecting mizani~=0.11.0 (from plotnine)
  Downloading mizani-0.11.4-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: numpy>=1.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotnine) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotnine) (1.13.1)
Requirement already satisfied: statsmodels>=0.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotnine) (0.14.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (23.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.7.0->plotnine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=2.1.0->plotnine) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=2.1.0->plotnine) (2023.3)
Requirement already satisfied: patsy>=0.5.6 in /opt/anaconda3/lib/python3.12/site-packages (from statsmodels>=0.14.0->plotnine) (0.5.6)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.12/site-packages (from patsy>=0.5.6->statsmodels>=0.14.0->plotnine) (1.16.0)
Downloading plotnine-0.13.6-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 11.5 MB/s eta 0:00:00a 0:00:01
Downloading mizani-0.11.4-py3-none-any.whl (127 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.4/127.4 kB 11.8 MB/s eta 0:00:00
Installing collected packages: mizani, plotnine
Successfully installed mizani-0.11.4 plotnine-0.13.6

## Load data

In [15]:
## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")

## create report_dt column
df['report_dt'] = pd.to_datetime(df.REPORT_DAT)

## Warm-up Demo

In [20]:
%%time # loop
for i in range(df.shape[0]):
    r = df.iloc[i]
    r.X + r.Y

CPU times: user 1.11 s, sys: 6.22 ms, total: 1.12 s
Wall time: 1.13 s

In [22]:
%%time # iterrows
for i,r in df.iterrows():
    r.X + r.Y

CPU times: user 628 ms, sys: 18.9 ms, total: 647 ms
Wall time: 663 ms

In [23]:
%%time # lambda
df.apply(lambda r: r.X + r.Y, axis = 1)

CPU times: user 234 ms, sys: 6.49 ms, total: 240 ms
Wall time: 240 ms

0       -38.114105
1       -38.125487
2       -38.084228
3       -38.065981
4       -38.045047
           ...
27926   -38.106420
27927   -38.113307
27928   -38.121112
27929   -38.108484
27930   -38.151707
Length: 27931, dtype: float64

In [26]:
%%time
## Super fast, but only works with built-in numpy functions.
df.X + df.Y

CPU times: user 1.08 ms, sys: 1.38 ms, total: 2.46 ms
Wall time: 2.29 ms

0       -38.114105
1       -38.125487
2       -38.084228
3       -38.065981
4       -38.045047
           ...
27926   -38.106420
27927   -38.113307
27928   -38.121112
27929   -38.108484
27930   -38.151707
Length: 27931, dtype: float64

# Practice

In [51]:
## define crimes to look for and crimes to look within
## CCN is Central Complaint Number: https://go.mpdconline.com/GO/GO_401_01.pdf
CCN_examples = ['20165648', '20123250']
C_Tar = C_Target = crimes_lookfor = df[df.CCN.astype(str).isin(CCN_examples)][['CCN', 'WARD', 'OFFENSE', 'report_dt']]
C_Oth = C_Other  = other_crimes = df[~df.CCN.astype(str).isin(CCN_examples)]

## print crimes_lookfor
C_Tar.head()
# other_crimes.head()

            CCN  WARD              OFFENSE                 report_dt
941    20165648     6  MOTOR VEHICLE THEFT 2020-11-20 02:25:50+00:00
14013  20123250     2  MOTOR VEHICLE THEFT 2020-08-29 05:00:25+00:00

**Task**: we have two crimes we want to look for. We want to look in the remaining crime reports for crime reports that are:

- Located in the same ward as the two focal crimes
- Reported at the same time as the focal crime or up to 1000 minutes later (changed from slides which stated 20 mins since crime ids changed since last time so this long bandwidth helps us find matches!)

Solutions compare two ways to solve:

- Using a for loop
- Using a function

## 1. Loop approach

In [36]:
## create empty container to store results 
store_matches = {}

## loop through two example crimes
for i in range(C_Tar.shape[0]): # same as shape
    
    ## extract row
    r = one_row = C_Tar.iloc[i]

    ## first, subset to crimes in same ward
    same_wards = C_Oth[C_Oth.WARD == r.WARD]
    
    ## second, with those same-ward crimes, construct indicator for reported within 20 minutes
    ## (interpreting as after but could do either)
    ### substep: get time cutoff
    CUTOFF = r.report_dt +  timedelta(minutes=1200)
    
    ### substep: use that to subset
    same_wards_sametime = same_wards[(same_wards.report_dt >= r.report_dt) & 
                                    (same_wards.report_dt <= CUTOFF)].copy()
    
    ## third, store the results
    store_matches[str(one_row.CCN)] = same_wards_sametime
    
## finally, concatenate results into one df
all_matches = pd.concat(store_matches)
all_matches.head()

                        X          Y       CCN              REPORT_DAT  \
20165648 279   -77.005894  38.905167  20165986  2020/11/20 22:17:27+00
         1308  -76.999518  38.891483  20165709  2020/11/20 04:27:36+00
         4675  -76.997316  38.904969  20165805  2020/11/20 15:06:04+00
         11621 -77.015554  38.899950  20166039  2020/11/20 22:07:10+00
         15616 -76.997328  38.885141  20165798  2020/11/20 12:46:32+00

                   SHIFT  METHOD              OFFENSE  \
20165648 279     EVENING  OTHERS  MOTOR VEHICLE THEFT
         1308   MIDNIGHT  OTHERS  MOTOR VEHICLE THEFT
         4675        DAY  OTHERS         THEFT F/AUTO
         11621   EVENING  OTHERS          THEFT/OTHER
         15616       DAY  OTHERS          THEFT/OTHER

                                                     BLOCK    XBLOCK  \
20165648 279            1151 - 1199 BLOCK OF 1ST STREET NE  399489.0
         1308             100 - 199 BLOCK OF 5TH STREET NE  400042.0
         4675          600 - 699 BLOCK OF ORLEANS PLACE NE  400233.0
         11621  300 - 363 BLOCK OF MASSACHUSETTS AVENUE NW  398651.0
         15616   600 - 669 BLOCK OF PENNSYLVANIA AVENUE SE  400232.0

                  YBLOCK  ...  CENSUS_TRACT VOTING_PRECINCT   LATITUDE  \
20165648 279    137478.0  ...       10603.0    Precinct 144  38.905159
         1308   135959.0  ...        8200.0     Precinct 89  38.891475
         4675   137456.0  ...       10602.0     Precinct 83  38.904961
         11621  136899.0  ...        5900.0    Precinct 143  38.899942
         15616  135255.0  ...        6500.0     Precinct 89  38.885133

                LONGITUDE           BID              START_DATE  \
20165648 279   -77.005891          NOMA  2020/11/20 20:15:26+00
         1308  -76.999516           NaN  2020/11/20 03:02:27+00
         4675  -76.997314           NaN  2020/11/19 22:30:39+00
         11621 -77.015552      DOWNTOWN  2020/11/20 17:30:16+00
         15616 -76.997326  CAPITOL HILL  2020/11/19 23:43:15+00

                              END_DATE   OBJECTID  OCTO_RECORD_ID  \
20165648 279    2020/11/20 21:46:24+00  596093043             NaN
         1308                      NaN  596105470             NaN
         4675   2020/11/20 03:00:43+00  596362501             NaN
         11621  2020/11/20 22:08:28+00  596387673             NaN
         15616                     NaN  596402829             NaN

                               report_dt
20165648 279   2020-11-20 22:17:27+00:00
         1308  2020-11-20 04:27:36+00:00
         4675  2020-11-20 15:06:04+00:00
         11621 2020-11-20 22:07:10+00:00
         15616 2020-11-20 12:46:32+00:00

[5 rows x 26 columns]

# 1.5 Iterrow Approach

In [40]:
## create empty container to store results 
store_matches = {}

## loop through two example crimes
for i, r in C_Tar.iterrows(): # same as 

    ## subset to crimes in same ward
    same_wards = C_Oth[C_Oth.WARD == r.WARD]
    
    ## second, with those same-ward crimes, construct indicator for reported within 20 minutes
    ## (interpreting as after but could do either)
    ### substep: get time cutoff
    CUTOFF = r.report_dt +  timedelta(minutes=1200)
    
    ### substep: use that to subset
    same_wards_sametime = same_wards[(same_wards.report_dt >= r.report_dt) & 
                                    (same_wards.report_dt <= CUTOFF)].copy()
    
    ## third, store the results
    store_matches[str(one_row.CCN)] = same_wards_sametime
    
## finally, concatenate results into one df
all_matches = pd.concat(store_matches)
all_matches.head()

                        X          Y       CCN              REPORT_DAT  \
20123250 734   -77.039824  38.905656  20123507  2020/08/29 22:04:46+00
         9297  -77.027565  38.897353  20123609  2020/08/30 00:05:52+00
         14014 -77.040091  38.909646  20123389  2020/08/29 16:05:18+00
         14015 -77.050528  38.913354  20123422  2020/08/29 16:45:57+00
         18683 -77.021929  38.899129  20123419  2020/08/29 17:15:19+00

                  SHIFT  METHOD              OFFENSE  \
20123250 734    EVENING  OTHERS  MOTOR VEHICLE THEFT
         9297   EVENING  OTHERS  MOTOR VEHICLE THEFT
         14014      DAY  OTHERS         THEFT F/AUTO
         14015      DAY  OTHERS         THEFT F/AUTO
         18683      DAY  OTHERS          THEFT/OTHER

                                                BLOCK    XBLOCK    YBLOCK  \
20123250 734         1700 - 1779 BLOCK OF M STREET NW  396546.0  137533.0
         9297        1100 - 1199 BLOCK OF F STREET NW  397609.0  136611.0
         14014       1700 - 1799 BLOCK OF P STREET NW  396523.0  137976.0
         14015  2200 - 2399 BLOCK OF DECATUR PLACE NW  395618.0  138388.0
         18683       700 - 799 BLOCK OF 7TH STREET NW  398098.0  136808.0

                ...  CENSUS_TRACT VOTING_PRECINCT   LATITUDE  LONGITUDE  \
20123250 734    ...       10700.0     Precinct 17  38.905648 -77.039822
         9297   ...        5802.0    Precinct 129  38.897346 -77.027563
         14014  ...        5303.0     Precinct 15  38.909638 -77.040089
         14015  ...        4100.0     Precinct 13  38.913346 -77.050526
         18683  ...        5801.0    Precinct 129  38.899121 -77.021926

                            BID              START_DATE  \
20123250 734    GOLDEN TRIANGLE  2020/08/27 19:01:24+00
         9297          DOWNTOWN  2020/08/29 23:08:57+00
         14014              NaN  2020/08/28 22:00:23+00
         14015              NaN  2020/08/26 22:00:29+00
         18683         DOWNTOWN  2020/08/29 16:05:40+00

                              END_DATE   OBJECTID  OCTO_RECORD_ID  \
20123250 734    2020/08/29 19:00:05+00  596095073             NaN
         9297                      NaN  596376108             NaN
         14014  2020/08/29 08:00:27+00  596397251             NaN
         14015  2020/08/27 12:00:51+00  596397252             NaN
         18683  2020/08/29 16:08:33+00  596447637             NaN

                               report_dt
20123250 734   2020-08-29 22:04:46+00:00
         9297  2020-08-30 00:05:52+00:00
         14014 2020-08-29 16:05:18+00:00
         14015 2020-08-29 16:45:57+00:00
         18683 2020-08-29 17:15:19+00:00

[5 rows x 26 columns]

## 2. Function approach

Practice rewriting the above loop as a function

### 2.1 define the function

In [47]:
store_matches_2 = {}

def find_related_crimes(r): # imagine the function taking in one row as its sole variable
    # Your code here
    same_ward=C_Oth[ C_Oth['WARD']==r['WARD'] ]
    same_ward_same_time=same_ward[ (same_ward['report_dt']>=r['report_dt']) &
                                    (same_ward['report_dt']<=(r['report_dt']+timedelta(minutes=1200)))].copy()
    #the previous same_ward_same_time is not a new dataframe, but a slice/view of the original dataframe. 

    store_matches_2[str(r['CCN'])]=same_ward_same_time

### 2.2 apply it to one of the focal crimes

### 2.3 Use apply to cover all the other focal crimes